Fix build error on esp-idf v5.x
Fix:
fatal error: driver/i2c.h: No such file or directory

As described [here](https://github.com/espressif/esp-idf/issues/8799)
driver component must be required in order to use i2c.h.

ssd1306_display_driver.c compiles again.

Signed-off-by: Davide Bettio <davide@uninstall.it>